In [3]:
import yfinance as yf

# Ticker lists for 10 major countries (Equity ETFs)
us_tickers = ["SPY"]
china_tickers = ["MCHI"]
japan_tickers = ["EWJ"]
uk_tickers = ["EWU"]
germany_tickers = ["EWG"]
canada_tickers = ["EWC"]
india_tickers = ["INDA"]
france_tickers = ["EWQ"]
australia_tickers = ["EWA"]
brazil_tickers = ["EWZ"]

# Bond ETFs (popular selections)
bond_tickers = ["AGG", "BND", "TLT", "BNDX", "VCIT", "MUB", "VCSH"]

# Commodity ETFs (popular selections)
commodity_tickers = ["GLD", "SLV", "PDBC", "FTGC", 'BNO', 'USO', 'UNG']

# Combine all ticker lists into one for download
all_stock_tickers = (
    us_tickers +
    china_tickers +
    japan_tickers +
    uk_tickers +
    germany_tickers +
    canada_tickers +
    india_tickers +
    france_tickers +
    australia_tickers +
    brazil_tickers
)
all_bond_tickers = bond_tickers
all_commodity_tickers = commodity_tickers
all_tickers = all_stock_tickers + all_bond_tickers + all_commodity_tickers

# Function to download full historical data for each ticker
def download_full_history(tickers):
    # Download full history data for all tickers
    data = yf.download(tickers, period="max")  # Downloads full historical data
    return data

# Download full historical data for all tickers
full_history_data = download_full_history(all_tickers)

# Display data
#close_prices = full_history_data['Adj Close'] # no adj close price?
close_prices1 = full_history_data['Close']
close_prices1.head()

[*********************100%***********************]  24 of 24 completed

Ticker,AGG,BND,BNDX,BNO,EWA,EWC,EWG,EWJ,EWQ,EWU,...,MCHI,MUB,PDBC,SLV,SPY,TLT,UNG,USO,VCIT,VCSH
Date,,,,,,,,,,,,,,,,,,,,,
1993-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,24.526068,NaN,NaN,NaN,NaN,NaN
1993-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,24.700523,NaN,NaN,NaN,NaN,NaN
1993-02-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,24.752846,NaN,NaN,NaN,NaN,NaN
1993-02-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,25.014502,NaN,NaN,NaN,NaN,NaN
1993-02-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,25.119162,NaN,NaN,NaN,NaN,NaN

In [12]:
# SPY full history
spy_data_full = full_history_data.xs('SPY', level=1, axis=1)

# Close prices for SPY
spy_close_prices = full_history_data['Close']['SPY']
spy_close_prices.head()

Date
1993-01-29    24.526068
1993-02-01    24.700523
1993-02-02    24.752846
1993-02-03    25.014502
1993-02-04    25.119162
Name: SPY, dtype: float64